import Link from "next/link";

export default function Home() {
  return <><header className="nav"><Link className="brand" href="/">impact<b>.</b></Link><nav><Link href="#how">How it works</Link> &nbsp; <Link href="#causes">Causes</Link></nav><Link className="button" href="/auth">Join impact.</Link></header>
  <main><section className="hero"><div className="eyebrow">● GOLF, REIMAGINED FOR GOOD</div><h1>Every round<br />can <em>matter.</em></h1><p>Track your game. Back a cause you love. Enter a monthly prize draw built around the scores you earn.</p><Link className="button" href="/auth">Start your impact</Link><div className="orb" /></section><div className="bar">PLAY YOUR GAME &nbsp; ✦ &nbsp; CHANGE A LIFE &nbsp; ✦ &nbsp; WIN TOGETHER</div>
  <section id="how" className="section"><div className="eyebrow">● A SIMPLE, BETTER LOOP</div><h2>Give your golf<br />a bigger <em>why.</em></h2><div className="grid"><article className="card"><small>01</small><h3>Join the club</h3><p>Choose a plan and choose a cause you want to move forward.</p></article><article className="card"><small>02</small><h3>Log your five</h3><p>Keep your latest Stableford scores current. Your form powers your entry.</p></article><article className="card"><small>03</small><h3>Feel the upside</h3><p>Enter a monthly prize draw as a share of every membership reaches charities.</p></article></div></section>
  <section className="section dark"><div className="draw"><div><div className="eyebrow">● SEPTEMBER DRAW</div><h2>Good form.<br /><em>Real possibility.</em></h2><p>Match three, four, or five numbers to share this month’s prize pool.</p></div><div className="numbers">{[7,14,22,31,44].map(n=><i className="number" key={n}>{String(n).padStart(2,"0")}</i>)}</div></div></section>
  <section id="causes" className="section"><div className="eyebrow">● YOUR IMPACT, YOUR CHOICE</div><h2>Back what<br />moves <em>you.</em></h2><div className="grid">{[["Mind","Mental health for all"],["Shelter","A home for everyone"],["WWF","For a living planet"]].map(([name,text])=><article className="card" key={name}><h3>{name}</h3><p>{text}</p><Link href="/dashboard">Choose this cause →</Link></article>)}</div></section></main></>;
}
