import Link from "next/link";
import { SiteFooter, SiteHeader } from "@/components/site-header";
import { MembershipPlans } from "@/components/membership-button";
import { FeaturedCauses } from "@/components/featured-causes";

const signals=[
  ["01","Join the movement","Choose a monthly or yearly membership, then select a cause that feels personal."],
  ["02","Log the good rounds","Keep your five latest Stableford scores close. They are a simple record of your game."],
  ["03","Share the possibility","Join a transparent monthly draw and follow exactly where every prize tier goes."],
];

export default function Home(){return <><SiteHeader/><main><section className="hero-v2"><div className="hero-v2__content"><p className="eyebrow">GOLF, REIMAGINED FOR GOOD</p><h1>Every round<br/>can <em>matter.</em></h1><p className="hero-copy">A membership for people who care about their game and the bigger picture. Track your form, choose a cause, and join the monthly draw.</p><div className="hero-actions"><Link className="button" href="/auth">Start your impact <span>→</span></Link><Link className="text-link" href="/how-it-works">How it works <span>↘</span></Link></div><div className="impact-stat"><b>₹8,42,600</b><span>raised for member causes<br/>this month</span></div></div><div className="hero-art"><div className="hero-sun"/><article className="score-float"><small>LATEST ROUND <b>+4.2%</b></small><strong>38</strong><span>STABLEFORD POINTS <em>12 SEP</em></span></article><article className="cause-float"><i>♥</i><p>Your next payment sends <b>₹30</b> to</p><strong>Mind</strong><div><span/></div><small>₹1,48,800 raised together</small></article></div></section><div className="ticker"><span>PLAY YOUR GAME</span><i>✦</i><span>CHANGE A LIFE</span><i>✦</i><span>WIN TOGETHER</span><i>✦</i><span>PLAY YOUR GAME</span></div>
<section className="intro-block"><div><p className="eyebrow">A SIMPLE, BETTER LOOP</p><h2>Give your golf<br/>a bigger <em>why.</em></h2></div><div className="signal-grid">{signals.map(([number,title,copy])=><article key={number}><span>{number}</span><i>↗</i><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
<section className="membership-showcase"><div><p className="eyebrow">MEMBERSHIP, WITH MEANING</p><h2>Choose how<br/>you <em>give back.</em></h2><p>Each active membership contributes a fixed ₹100 to the monthly prize pool. You choose the cause that receives your charity contribution.</p></div><MembershipPlans /></section>
<section className="draw-banner"><div><p className="eyebrow eyebrow--light">SEPTEMBER DRAW</p><h2>Good form.<br/><em>Real possibility.</em></h2><p>Match three, four, or five numbers to share the monthly prize pool. Every tier is clear before the draw begins.</p><Link className="ghost-button" href="/draw">Explore the draw <b>→</b></Link></div><div className="draw-widget"><div><span>LIVE PRIZE POOL</span><b>₹42,800</b></div><section>{[7,14,22,31,44].map((value,index)=><i className={`ball ball-${index}`} key={value}>{String(value).padStart(2,"0")}</i>)}</section><footer><span>DRAW CLOSES IN 10 DAYS</span><span>5 · 4 · 3 MATCHES</span></footer></div></section>
<section className="causes-home"><div className="section-heading"><div><p className="eyebrow">YOUR IMPACT, YOUR CHOICE</p><h2>Back what<br/><em>moves you.</em></h2></div><Link className="text-link" href="/charities">See all causes <span>→</span></Link></div><FeaturedCauses /></section>
<section className="final-cta"><p className="eyebrow">MAKE THE NEXT ROUND COUNT</p><h2>Golf has always<br/>been <em>more.</em></h2><Link className="button" href="/auth">Become a member <span>→</span></Link></section></main><SiteFooter/></>}
