"use client";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { addScore, type Score } from "@/lib/scores";
type Charity={id:string;name:string}; type Props={userId:string;name:string};
export function DashboardClient({userId,name}:Props){const [scores,setScores]=useState<Score[]>([]);const [charities,setCharities]=useState<Charity[]>([]);const [cause,setCause]=useState("");const [percent,setPercent]=useState(10);const [message,setMessage]=useState("");const supabase=createClient();
 async function load(){const [{data:scoreRows},{data:charityRows},{data:choice}]=await Promise.all([supabase.from("scores").select("score_date,stableford_points").eq("user_id",userId).order("score_date",{ascending:false}),supabase.from("charities").select("id,name").order("name"),supabase.from("member_charities").select("charity_id,contribution_percent").eq("user_id",userId).maybeSingle()]);setScores((scoreRows||[]).map(s=>({date:s.score_date,points:s.stableford_points})));setCharities(charityRows||[]);if(choice){setCause(choice.charity_id);setPercent(Number(choice.contribution_percent));}}
 useEffect(()=>{load()},[]);
 async function saveScore(form:FormData){const candidate={date:String(form.get("date")),points:Number(form.get("points"))};const check=addScore(scores,candidate);if("error" in check){setMessage(check.error);return}const {error}=await supabase.from("scores").insert({user_id:userId,score_date:candidate.date,stableford_points:candidate.points});if(error){setMessage(error.message);return}setMessage("Score saved. Your latest five entries are retained.");await load();}
 async function saveCause(){if(!cause||percent<10||percent>100){setMessage("Select a cause and enter a percentage from 10 to 100.");return}const {error}=await supabase.from("member_charities").upsert({user_id:userId,charity_id:cause,contribution_percent:percent});setMessage(error?error.message:"Your charity choice is saved.")}
 return <><div className="dashboard-grid"><article className="panel"><small>MEMBERSHIP</small><h3>Choose a plan</h3><p>Activate monthly or yearly membership via Stripe.</p><b>Subscription required</b></article><article className="panel"><small>YOUR CAUSE</small><h3>{charities.find(c=>c.id===cause)?.name||"Not selected"}</h3><p>{percent}% contribution</p><b>Minimum 10%</b></article><article className="panel"><small>NEXT DRAW</small><h3>September 2026</h3><p>Active subscribers with five scores are entered.</p><b>{scores.length}/5 scores saved</b></article><article className="panel"><small>WINNINGS</small><h3>£0.00</h3><p>Total won to date</p><b>No payment pending</b></article></div><section className="scores"><div className="eyebrow">YOUR LAST FIVE</div><h3>Form tracker</h3><p>Stableford scores must be 1-45; duplicate dates are not allowed.</p><div className="score-list">{scores.map(s=><div className="score" key={s.date}>{s.points}<span>{new Date(s.date+"T00:00:00").toLocaleDateString("en-GB",{day:"2-digit",month:"short"})}</span></div>)}</div><form action={saveScore}><label>Date<input name="date" type="date" required /></label><label>Stableford score<input name="points" type="number" min="1" max="45" required placeholder="1-45" /></label><button className="button">Save score</button></form></section><section className="panel choice"><div><div className="eyebrow">CHARITY CONTRIBUTION</div><h3>Direct your impact</h3></div><label>Charity<select value={cause} onChange={e=>setCause(e.target.value)}><option value="">Choose a charity</option>{charities.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Contribution %<input value={percent} min="10" max="100" type="number" onChange={e=>setPercent(Number(e.target.value))}/></label><button className="button" onClick={saveCause}>Save choice</button></section>{message&&<p className="message">{message}</p>}</>;
}
